.\" Manpage for hangman.
.\" Contact jrviner2000@gmail.com to correct errors or typos.
.TH man 6 "05 Nov 2022" "1.0" "hangman man page"
.SH NAME
hangman \- interactively play hangman in-console
.SH SYNOPSIS
hangman [FILE]
.SH DESCRIPTION
Hangman plays the word-guessing game hangman in the console interactively 

The object of the game is to guess a word taken from a wordbank, one character at a time. The game will show an amount of spaces equal to the number of letters in the selected word and upon receiving a letter from the user will reveal all instances of that letter in the word. The game ends when either the user has entered five incorrect guesses or successfully guesses every letter in the word.

Upon finishing a game, the program saves gameplay statistics including total games played, win/loss record, average score per game, and time spent playing. The statistics are shown at the start of a new game.

The default FILE is $HOME/.words, but a custom path can be specified to the desired word bank. 

Only words that contain any combination of letters and punctuation are considered valid and other words that do not fit these criteria will be ignored.

